### PR TITLE
change external-tools clone repo per #149

### PR DESCRIPTION
**Pull request by smigad**
change external-tools clone repo per singnet/virtual-assistant#149

### CODE REVIEW

**Comment by smigad** [comment]
@ferrouswheel this can be merged right?

**Comment by ferrouswheel** [comment]
I'm unsure why we need a separate branch, inside a fork, for storing this change.

Can't we just add options to the script and keep things in one place?

**Comment by smigad** [comment]
my thinking was to keep the script working as it is for normal cases (with its camel case concept names and all) but only use the changes specifically for the VA needs. 
Should it be in master and an optional command line argument enforces the changes VA needs?

**Comment by ferrouswheel** [comment]
I think that would be preferable. Otherwise the branches could diverge.

**Comment by smigad** [comment]
@ferrouswheel sorry about the last commit it was to fix an oversight during the last commit. A squash-merge might be better for this PR.

**Comment by ferrouswheel** [comment]
Thanks - done :-)

**Pull request merged**
